#!/usr/bin/csh
source /apps/design_environment.csh
set test_name="$1"
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value +incdir+../package  +incdir+../test +incdir+../top +incdir+../seq +incdir+../uvc ../top/smc_top.sv -l smc_compile.log 
./simv -l smc_sim.log +UVM_TESTNAME=$test_name +UVM_VERBOSITY=UVM_LOW
